// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvoDgBsWxKpMPV4DVv0v1TURymmmZyy74',
    appId: '1:678882711233:web:4f7a03c274a9a8b589a640',
    messagingSenderId: '678882711233',
    projectId: 'quiz-app-bd447',
    authDomain: 'quiz-app-bd447.firebaseapp.com',
    storageBucket: 'quiz-app-bd447.firebasestorage.app',
    measurementId: 'G-DKVT0KLBCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXVanV6PgK2pQvNUjjuXPZupXfkk4_i70',
    appId: '1:678882711233:android:34968d9333e2908189a640',
    messagingSenderId: '678882711233',
    projectId: 'quiz-app-bd447',
    storageBucket: 'quiz-app-bd447.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd47VlTIj_GopOUkY23yycom9OFp4CISk',
    appId: '1:678882711233:ios:d64b5868a68eb60c89a640',
    messagingSenderId: '678882711233',
    projectId: 'quiz-app-bd447',
    storageBucket: 'quiz-app-bd447.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd47VlTIj_GopOUkY23yycom9OFp4CISk',
    appId: '1:678882711233:ios:d64b5868a68eb60c89a640',
    messagingSenderId: '678882711233',
    projectId: 'quiz-app-bd447',
    storageBucket: 'quiz-app-bd447.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvoDgBsWxKpMPV4DVv0v1TURymmmZyy74',
    appId: '1:678882711233:web:27d1ada67ae8e2ef89a640',
    messagingSenderId: '678882711233',
    projectId: 'quiz-app-bd447',
    authDomain: 'quiz-app-bd447.firebaseapp.com',
    storageBucket: 'quiz-app-bd447.firebasestorage.app',
    measurementId: 'G-353PMWXF36',
  );
}
